import { GoogleGenAI, Type } from "@google/genai";
import { getAdminDb } from "@/lib/firebase-admin";
import { calculateOffers, SimulationParams } from "@/lib/simulation-engine";

// Initialization logic
const getAI = () => {
    const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY || '';
    if (!apiKey || apiKey.includes("MY_GEMINI")) {
        console.warn("Invalid or missing API Key for Gemini");
    }
    return new GoogleGenAI({ apiKey });
};

// Tool definition for Gemini
const calculateLoanOffersTool = {
    name: "calculate_client_loan_offers",
    description: "Calculates the best loan portability offers based on customer data. Call this when you have collected professional details: convenio, idade, bancoAtual, valorParcela, saldoDevedor, prazoTotal, parcelasPagas, etc.",
    parameters: {
        type: Type.OBJECT,
        properties: {
            idade: { type: Type.NUMBER, description: "Customer age" },
            convenio: { type: Type.STRING, description: "Agreement type (e.g., INSS, SIAPE, GOVERNO)" },
            subConvenio: { type: Type.STRING, description: "Sub-agreement (e.g., Marinha, Exercito)" },
            codigoBeneficio: { type: Type.STRING, description: "Benefit code" },
            dataConcessao: { type: Type.STRING, description: "Benefit concession date/year (e.g., '1995', '20-10-2020')" },
            bancoAtual: { type: Type.STRING, description: "Current bank name or code" },
            valorParcela: { type: Type.NUMBER, description: "Current monthly installment value" },
            saldoDevedor: { type: Type.NUMBER, description: "Current balance to be paid" },
            prazoTotal: { type: Type.NUMBER, description: "Total terms (e.g., 84, 96)" },
            parcelasPagas: { type: Type.NUMBER, description: "Installments already paid" },
            parcelasRestantes: { type: Type.NUMBER, description: "Remaining installments" },
            isAnalfabeto: { type: Type.BOOLEAN, description: "If the customer is illiterate" },
            isCliente60Mais: { type: Type.BOOLEAN, description: "If the customer is 60+ AND resides in AP, PB, TO or RR" },
            hasTwoCards: { type: Type.BOOLEAN, description: "If the client has 2 active cards (only applicable to INSS)" },
            negativeCardValue: { type: Type.NUMBER, description: "The negative margin generated by the cards (only if hasTwoCards is true)" }
        },
        required: ["idade", "convenio", "bancoAtual", "valorParcela", "saldoDevedor", "prazoTotal"]
    }
};

function calculateInterestRateAgent(pv: number, pmt: number, n: number) {
    if (pmt <= 0 || pv <= 0 || n <= 0) return 0;
    let low = 0.0001; let high = 1; let rate = 0.05; let diff = 1;
    let iterations = 0;
    while (diff > 0.0001 && high - low > 0.00001 && iterations < 100) {
        const calculatedPv = (pmt / rate) * (1 - Math.pow(1 + rate, -n));
        diff = Math.abs(calculatedPv - pv);
        if (calculatedPv > pv) { low = rate; rate = (rate + high) / 2; }
        else { high = rate; rate = (rate + low) / 2; }
        iterations++;
    }
    return rate;
}

let cachedBankRulesText = '';
let lastCacheTime = 0;

export async function processWhatsAppMessage(message: string, history: any[] = [], currentPhone: string = '') {
    const ai = getAI();
    if (!ai || (ai as any).error) {
        return `DEBUG_NULL_AI: ${(ai as any)?.error || "unknown"}`;
    }

    // Primeira mensagem
    if (history.length === 0) {
        return `Olá! Eu sou o *Gutto*, seu especialista em portabilidade de crédito consignado.\n\nVocê pode:\n• *Iniciar uma simulação* – basta dizer "Quero simular".\n• *Consultar regras* – peça o "resumo das regras" ou pergunte sobre um banco.\n\nComo posso ajudar?`;
    }

    // Consulta de Regras
    const lowerMsg = message.toLowerCase();
    const asksForRules = /\b(resumo|regras|informações?|detalhes?)\b/.test(lowerMsg) || (/\b(banco|instituição)\b/.test(lowerMsg) && !history.some(h => h.content.includes("Troco Estimado")));
    
    if (asksForRules) {
        if (!cachedBankRulesText) {
            try {
                const adminDb = getAdminDb();
                if (adminDb) {
                    const snap = await adminDb.collection('bankRules').get();
                    let txt = '';
                    snap.forEach(d => {
                        const dta = d.data();
                        if (dta.isActive !== false) {
                            txt += `- ${dta.name}: Idade ${dta.minAge || 18} a ${dta.maxAge || 80} anos. `;
                            if (dta.portabilityRate) txt += `Taxa mín. Portabilidade: ${dta.portabilityRate}%. `;
                            if (dta.refinRate) txt += `Taxa Refin: ${dta.refinRate}%. `;
                            if (dta.minBalance) txt += `Saldo mín.: R$ ${dta.minBalance}. `;
                            if (dta.minTroco) txt += `Troco mín.: R$ ${dta.minTroco}. `;
                            if (dta.minInstallmentValue) txt += `Parcela mín.: R$ ${dta.minInstallmentValue}. `;
                            txt += '\n';
                        }
                    });
                    cachedBankRulesText = txt;
                }
            } catch (e) { /* ignore */ }
        }
        return `📝 *Resumo das regras dos bancos*:\n${cachedBankRulesText}\nSe quiser detalhes de algum banco específico, basta informar o nome dele.`;
    }

    let userProfileForSimulation = { role: 'admin' } as any;

    // Validate phone
    if (currentPhone) {
        const cleanPhone = currentPhone.replace(/\D/g, ''); 
        const adminDb = getAdminDb();
        if (adminDb) {
            const usersRef = await adminDb.collection('users').get();
            let foundUser = null;
            usersRef.forEach(doc => {
                const userData = doc.data();
                if (userData.phone) {
                    const cleanDbPhone = userData.phone.replace(/\D/g, '');
                    if (cleanDbPhone.length >= 8 && cleanPhone.endsWith(cleanDbPhone)) {
                        foundUser = { uid: doc.id, ...userData };
                    }
                }
            });
            if (!foundUser) return "Desculpe, seu número não está cadastrado.";
            userProfileForSimulation = foundUser;
        }
    }

    // Cache de Regras
    const now = Date.now();
    if (now - lastCacheTime > 5 * 60 * 1000) {
        try {
            const adminDb = getAdminDb();
            if (adminDb) {
                const banksSnap = await adminDb.collection('bankRules').get();
                let rulesText = 'RESUMO DAS REGRAS DOS BANCOS:\n';
                banksSnap.forEach(doc => {
                    const data = doc.data();
                    if (data.isActive !== false) {
                        rulesText += `- ${data.name}: Idade ${data.minAge || 18} a ${data.maxAge || 80} anos. `;
                        if (data.portabilityRate) rulesText += `Taxa mín. Portabilidade: ${data.portabilityRate}%. `;
                        if (data.refinRate) rulesText += `Taxa Refin: ${data.refinRate}%. `;
                        if (data.minBalance) rulesText += `Saldo mín: R$ ${data.minBalance}. `;
                        if (data.minTroco) rulesText += `Troco mín: R$ ${data.minTroco}. `;
                        if (data.minInstallmentValue) rulesText += `Parcela mín: R$ ${data.minInstallmentValue}. `;
                        if (data.nonAcceptedBanks && data.nonAcceptedBanks.length > 0) rulesText += `Bancos que NÃO aceita: ${data.nonAcceptedBanks.join(', ')}. `;
                        rulesText += '\n';
                    }
                });
                cachedBankRulesText = rulesText;
                lastCacheTime = now;
            }
        } catch (e) { console.error(e); }
    }

    const systemInstruction = `Você é o "Gutto", Agente de IA da Portabilidade PRO.

ESTADO DA CONVERSA:
1. Verifique o histórico para ver o que já foi coletado.
2. Se você já apresentou o resultado (Troco Estimado) e o usuário pedir "Outro Banco" ou o nome de um banco da lista, VOCÊ DEVE chamar a ferramenta 'calculate_client_loan_offers' novamente, mantendo os dados e trocando apenas o 'bancoAtual'.
3. Faça apenas UMA pergunta por vez.

FLUXO DE COLETA:
1. Convênio e Idade.
2. Localidade se 60+.
3. Sub-convênio/Espécie.
4. Cartões (apenas INSS).
5. Analfabeto.
6. Banco Atual.
7. Prazo Total.
8. Prazo Restante.
9. Valor da Parcela.
10. Saldo Devedor.

REGRAS CRÍTICAS:
- Assim que tiver o 'Saldo Devedor' ou o usuário pedir outro banco da lista, chame a ferramenta 'calculate_client_loan_offers'.
- NUNCA invente valores. Use apenas o que a ferramenta retornar.

LAYOUT DE RESPOSTA (OBRIGATÓRIO):
Encontramos uma oferta ideal para você no *[NOME DO BANCO]*:
⭐ *[tabelasCount] tabelas disponíveis*

📊 *Tabela:* [tabela]
💰 *Troco Estimado:* R$ [valorTroco]
📄 *Novo Contrato:* R$ [valorContrato]
💲 *Valor da Parcela:* R$ [valor da parcela]
⏳ *Prazo do Refin/Port:* [prazoRefinPort] meses
📈 *Taxa do Refinanciamento:* [taxaBase]%

Outros Bancos: [BANCO 2], [BANCO 3]

OPÇÕES:
- Digite *Tabelas* para ver outras opções deste banco.
- Digite o *Nome de outro Banco* para ver detalhes dele.

---
REGRAS (Para consulta):
${cachedBankRulesText}`;

    try {
        const contents = [
            ...history.map(h => ({
                role: h.role === 'user' ? 'user' : 'model',
                parts: [{ text: h.content }]
            })),
            { role: "user", parts: [{ text: message }] }
        ];

        const result = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents,
            config: {
                systemInstruction,
                tools: [{ functionDeclarations: [calculateLoanOffersTool] }]
            }
        });

        const candidates = (result as any).candidates || (result as any).response?.candidates;
        const firstCandidate = candidates?.[0];
        const parts = firstCandidate?.content?.parts || [];
        const functionCalls = parts.filter((p: any) => p.functionCall).map((p: any) => p.functionCall);

        if (functionCalls && functionCalls.length > 0 && functionCalls[0].name === "calculate_client_loan_offers") {
            const call = functionCalls[0];
            const params = call.args as unknown as SimulationParams;

            // Business logic for 2 cards
            if (params.convenio === 'INSS' && (params as any).hasTwoCards) {
                const desconto = (params as any).negativeCardValue || 81.05;
                params.valorParcela = Math.max(0, (params.valorParcela || 0) - desconto);
            }

            // Interest rate calculation fallback
            if (!params.taxaJurosMensal) {
                const pmt = params.valorParcela || 0;
                const pv = params.saldoDevedor || 0;
                const pagas = params.parcelasPagas || 0;
                const total = params.prazoTotal || 0;
                const n = params.parcelasRestantes || (total > 0 ? total - pagas : 0);
                if (pmt > 0 && pv > 0 && n > 0) {
                    params.taxaJurosMensal = calculateInterestRateAgent(pv, pmt, n);
                }
            }

            const adminDb = getAdminDb();
            if (!adminDb) return "⚠️ Erro de conexão com o banco.";

            const [banksSnap, rulesSnap, settingsSnap] = await Promise.all([
                adminDb.collection('bankRules').get(),
                adminDb.collection('generalRules').get(),
                adminDb.collection('settings').doc('admin').get()
            ]);

            const banks = banksSnap.docs.map(d => ({ id: d.id, ...d.data() }));
            const rules = rulesSnap.docs.map(d => ({ id: d.id, ...d.data() }));
            const settingsData = settingsSnap.exists ? settingsSnap.data() : {};
            const promotoraPriorities = settingsData?.bankPriorities || {};
            const promotoraInstallments = settingsData?.bankInstallments || {};

            const allOffers = calculateOffers(params, banks, rules, promotoraPriorities, promotoraInstallments, userProfileForSimulation);

            // Grouping and Sorting
            const bankGroups = allOffers.reduce((acc, offer) => {
                if (!acc[offer.name]) acc[offer.name] = { bankName: offer.name, offers: [] };
                acc[offer.name].offers.push(offer);
                return acc;
            }, {} as Record<string, { bankName: string, offers: any[] }>);

            const groupedBanks = Object.values(bankGroups).map(group => {
                const sorted = group.offers.sort((a, b) => a.valorTroco - b.valorTroco);
                return { ...group, offers: sorted, topOffer: sorted[0] };
            }).sort((a, b) => {
                const pA = promotoraPriorities[a.topOffer.id.split('-')[0]] ?? a.topOffer.priority ?? 999;
                const pB = promotoraPriorities[b.topOffer.id.split('-')[0]] ?? b.topOffer.priority ?? 999;
                if (pA !== pB) return (pA || 999) - (pB || 999);
                return a.topOffer.valorTroco - b.topOffer.valorTroco;
            });

            const sanitize = (o: any) => o ? { ...o, logo: undefined } : null;
            const topOffer = sanitize(groupedBanks.length > 0 ? groupedBanks[0].topOffer : null);
            const otherBanks = groupedBanks.map(g => g.bankName);
            const sampleOffers = groupedBanks.map(g => sanitize(g.topOffer)).slice(0, 10);

            // Save simulation
            const simId = crypto.randomUUID();
            try {
                await adminDb.collection('simulations').doc(simId).set({
                    userId: userProfileForSimulation.uid || 'bot',
                    userName: userProfileForSimulation.name || 'WhatsApp',
                    userAvatar: userProfileForSimulation.logoUrl || userProfileForSimulation.avatarUrl || '',
                    convenio: params.convenio,
                    valorParcela: params.valorParcela,
                    saldoDevedor: params.saldoDevedor,
                    selectedOffer: topOffer,
                    topOffer: topOffer?.name || '',
                    createdAt: new Date(),
                    origin: 'whatsapp'
                });
            } catch (e) { console.error(e); }

            const followUp = await ai.models.generateContent({
                model: "gemini-3-flash-preview",
                contents: [
                    ...contents,
                    firstCandidate?.content || { role: "model", parts: [{ text: "" }] },
                    {
                        role: "user",
                        parts: [{
                            functionResponse: {
                                name: "calculate_client_loan_offers",
                                response: {
                                    offersCount: allOffers.length,
                                    banksCount: otherBanks.length,
                                    bestTroco: topOffer,
                                    allBanksWithOffers: otherBanks,
                                    sampleOffers,
                                    otherTablesOfBestBank: groupedBanks.length > 0 ? groupedBanks[0].offers.slice(1, 6).map(sanitize) : []
                                }
                            }
                        }]
                    }
                ],
                config: { systemInstruction }
            });

            return followUp.text || "Encontrei propostas interessantes!";
        }

        return firstCandidate?.content?.parts?.[0]?.text || (result as any).text || "Como posso ajudar?";

    } catch (error: any) {
        console.error(error);
        return `DEBUG_ERROR: ${error.message}`;
    }
}
