import { GoogleGenAI, Type } from "@google/genai";
import { getAdminDb } from "@/lib/firebase-admin";
import { calculateOffers, SimulationParams } from "@/lib/simulation-engine";

// Initialization logic
const getAI = () => {
    const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY || '';
    if (!apiKey || apiKey.includes("MY_GEMINI")) {
        console.warn("Invalid or missing API Key for Gemini");
    }
    return new GoogleGenAI({ apiKey });
};

// Tool definition for Gemini
const calculateLoanOffersTool = {
    name: "calculate_client_loan_offers",
    description: "Calculates the best loan portability offers based on customer data. Call this when you have collected professional details: convenio, idade, bancoAtual, valorParcela, saldoDevedor, prazoTotal, parcelasPagas, etc.",
    parameters: {
        type: Type.OBJECT,
        properties: {
            idade: { type: Type.NUMBER, description: "Customer age" },
            convenio: { type: Type.STRING, description: "Agreement type (e.g., INSS, SIAPE, GOVERNO)" },
            subConvenio: { type: Type.STRING, description: "Sub-agreement (e.g., Marinha, Exercito)" },
            codigoBeneficio: { type: Type.STRING, description: "Benefit code" },
            dataConcessao: { type: Type.STRING, description: "Benefit concession date/year (e.g., '1995', '20-10-2020')" },
            bancoAtual: { type: Type.STRING, description: "Current bank name or code" },
            valorParcela: { type: Type.NUMBER, description: "Current monthly installment value" },
            saldoDevedor: { type: Type.NUMBER, description: "Current balance to be paid" },
            prazoTotal: { type: Type.NUMBER, description: "Total terms (e.g., 84, 96)" },
            parcelasPagas: { type: Type.NUMBER, description: "Installments already paid" },
            parcelasRestantes: { type: Type.NUMBER, description: "Remaining installments" },
            isAnalfabeto: { type: Type.BOOLEAN, description: "If the customer is illiterate" },
            isCliente60Mais: { type: Type.BOOLEAN, description: "If the customer is 60+ AND resides in AP, PB, TO or RR" },
            hasTwoCards: { type: Type.BOOLEAN, description: "If the client has 2 active cards (only applicable to INSS)" },
            negativeCardValue: { type: Type.NUMBER, description: "The negative margin generated by the cards (only if hasTwoCards is true)" }
        },
        required: ["idade", "convenio", "bancoAtual", "valorParcela", "saldoDevedor", "prazoTotal"]
    }
};

function calculateInterestRateAgent(pv: number, pmt: number, n: number) {
    if (pmt <= 0 || pv <= 0 || n <= 0) return 0;
    let low = 0.0001; let high = 1; let rate = 0.05; let diff = 1;
    let iterations = 0;
    while (diff > 0.0001 && high - low > 0.00001 && iterations < 100) {
        const calculatedPv = (pmt / rate) * (1 - Math.pow(1 + rate, -n));
        diff = Math.abs(calculatedPv - pv);
        if (calculatedPv > pv) { low = rate; rate = (rate + high) / 2; }
        else { high = rate; rate = (rate + low) / 2; }
        iterations++;
    }
    return rate;
}

let cachedBankRulesText = '';
let lastCacheTime = 0;

export async function processWhatsAppMessage(message: string, history: any[] = [], currentPhone: string = '') {
    const ai = getAI();
    if (!ai || (ai as any).error) {
        return `DEBUG_NULL_AI: ${(ai as any)?.error || "unknown"}`;
    }

    // Primeira mensagem
    if (history.length === 0) {
        return `Olá! Eu sou o *Gutto*, seu especialista em portabilidade de crédito consignado.\n\nVocê pode:\n• *Iniciar uma simulação* – basta dizer "Quero simular".\n• *Consultar regras* – peça o "resumo das regras" ou pergunte sobre um banco.\n\nComo posso ajudar?`;
    }

    // Consulta de Regras
    const lowerMsg = message.toLowerCase();
    const asksForRules = /\b(resumo|regras|informações?|detalhes?)\b/.test(lowerMsg) || (/\b(banco|instituição)\b/.test(lowerMsg) && !history.some(h => h.content.includes("Troco Estimado")));
    
    if (asksForRules) {
        if (!cachedBankRulesText) {
            try {
                const adminDb = getAdminDb();
                if (adminDb) {
                    const snap = await adminDb.collection('bankRules').get();
                    let txt = '';
                    snap.forEach(d => {
                        const dta = d.data();
                        if (dta.isActive !== false) {
                            txt += `- ${dta.name}: Idade ${dta.minAge || 18} a ${dta.maxAge || 80} anos. `;
                            if (dta.portabilityRate) txt += `Taxa mín. Portabilidade: ${dta.portabilityRate}%. `;
                            if (dta.refinRate) txt += `Taxa Refin: ${dta.refinRate}%. `;
                            if (dta.minBalance) txt += `Saldo mín.: R$ ${dta.minBalance}. `;
                            if (dta.minTroco) txt += `Troco mín.: R$ ${dta.minTroco}. `;
                            if (dta.minInstallmentValue) txt += `Parcela mín.: R$ ${dta.minInstallmentValue}. `;
                            txt += '\n';
                        }
                    });
                    cachedBankRulesText = txt;
                }
            } catch (e) { /* ignore */ }
        }
        return `📝 *Resumo das regras dos bancos*:\n${cachedBankRulesText}\nSe quiser detalhes de algum banco específico, basta informar o nome dele.`;
    }

    let userProfileForSimulation = { role: 'admin' } as any;

    // Validate phone
    if (currentPhone) {
        const cleanPhone = currentPhone.replace(/\D/g, ''); 
        const adminDb = getAdminDb();
        if (adminDb) {
            const usersRef = await adminDb.collection('users').get();
            let foundUser = null;
            usersRef.forEach(doc => {
                const userData = doc.data();
                if (userData.phone) {
                    const cleanDbPhone = userData.phone.replace(/\D/g, '');
                    if (cleanDbPhone.length >= 8 && cleanPhone.endsWith(cleanDbPhone)) {
                        foundUser = { uid: doc.id, ...userData };
                    }
                }
            });
            if (!foundUser) return "Desculpe, seu número não está cadastrado.";
            userProfileForSimulation = foundUser;
        }
    }

    // Cache de Regras
    const now = Date.now();
    if (now - lastCacheTime > 5 * 60 * 1000) {
        try {
            const adminDb = getAdminDb();
            if (adminDb) {
                const banksSnap = await adminDb.collection('bankRules').get();
                let rulesText = 'RESUMO DAS REGRAS DOS BANCOS:\n';
                banksSnap.forEach(doc => {
                    const data = doc.data();
                    if (data.isActive !== false) {
                        rulesText += `- ${data.name}: Idade ${data.minAge || 18} a ${data.maxAge || 80} anos. `;
                        if (data.portabilityRate) rulesText += `Taxa mín. Portabilidade: ${data.portabilityRate}%. `;
                        if (data.refinRate) rulesText += `Taxa Refin: ${data.refinRate}%. `;
                        if (data.minBalance) rulesText += `Saldo mín: R$ ${data.minBalance}. `;
                        if (data.minTroco) rulesText += `Troco mín: R$ ${data.minTroco}. `;
                        if (data.minInstallmentValue) rulesText += `Parcela mín: R$ ${data.minInstallmentValue}. `;
                        if (data.nonAcceptedBanks && data.nonAcceptedBanks.length > 0) rulesText += `Bancos que NÃO aceita: ${data.nonAcceptedBanks.join(', ')}. `;
                        rulesText += '\n';
                    }
                });
                cachedBankRulesText = rulesText;
                lastCacheTime = now;
            }
        } catch (e) { console.error(e); }
    }

    const systemInstruction = `Você é o "Gutto", o Agente de IA especialista em Portabilidade da Portabilidade PRO.

PROTOCOLO DE COLETA (OBRIGATÓRIO):
1. Analise o histórico de mensagens INTEGRALMENTE antes de responder.
2. Se o dado já foi informado pelo usuário em qualquer momento da conversa, considere-o coletado e NÃO pergunte novamente.
3. Faça estritamente APENAS UMA pergunta por vez. NUNCA use "e" para pedir dois dados (Ex: "Qual seu convenio e idade?" é PROIBIDO).
4. Siga a ordem abaixo. Se já tiver o dado 1, peça o 2. Se tiver o 2, peça o 3, e assim por diante.

ORDEM DE COLETA:
1. Convênio (INSS, SIAPE, Governo, etc.)
2. Idade (apenas o número)
3. Localidade (Se Idade >= 60, pergunte: "Você reside em AP, PB, TO ou RR?")
4. Sub-convênio/Espécie (conforme o convênio)
5. Analfabeto (Sim ou Não)
6. Cartões Ativos (Se INSS, pergunte: "Possui os 2 cartões ativos? Qual o valor do desconto?")
7. Banco Atual (Onde está o contrato hoje)
8. Prazo Total (Quantas parcelas no total, ex: 84 ou 96)
9. Valor da Parcela (Quanto paga por mês)
10. Saldo Devedor -> AO RECEBER ESTE DADO, CHAME A FERRAMENTA 'calculate_client_loan_offers' IMEDIATAMENTE.

REGRAS CRÍTICAS:
- Se o usuário informar o nome de outro banco da lista após o resultado, chame a ferramenta de novo IMEDIATAMENTE usando os dados que você já tem.
- Se o resultado for "banksCount: 0", diga que não há ofertas e encerre.
- NÃO invente regras. Se não souber, consulte a seção de REGRAS abaixo.

LAYOUT DE RESPOSTA (RESULTADO):
Encontramos uma oferta ideal para você no *[NOME DO BANCO]*:
⭐ *[tabelasCount] tabelas disponíveis*

📊 *Tabela:* [tabela]
💰 *Troco Estimado:* R$ [valorTroco]
📄 *Novo Contrato:* R$ [valorContrato]
💲 *Valor da Parcela:* R$ [valor da parcela]
⏳ *Prazo do Refin/Port:* [prazoRefinPort] meses
📈 *Taxa do Refinanciamento:* [taxaBase]%

Outros Bancos: [BANCO 2], [BANCO 3]

---
REGRAS DOS BANCOS (Para consulta):
${cachedBankRulesText}`;

    try {
        const contents = [
            ...history.map(h => ({
                role: h.role === 'user' ? 'user' : 'model',
                parts: [{ text: h.content }]
            })),
            { role: "user", parts: [{ text: message }] }
        ];

        const result = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents,
            config: {
                systemInstruction,
                tools: [{ functionDeclarations: [calculateLoanOffersTool] }]
            }
        });

        // Detecção ultra-robusta de Function Call
        const candidates = (result as any).candidates || (result as any).response?.candidates || [];
        const firstCandidate = candidates[0];
        const parts = firstCandidate?.content?.parts || [];
        
        // Verifica tanto pela propriedade oficial quanto pelo parsing manual dos parts
        let callPart = parts.find((p: any) => p.functionCall);
        const functionCalls = callPart ? [callPart.functionCall] : ((result as any).functionCalls || []);

        if (functionCalls && functionCalls.length > 0 && functionCalls[0].name === "calculate_client_loan_offers") {
            const call = functionCalls[0];
            const params = call.args as unknown as SimulationParams;

            // Regra dos 2 cartões
            if (params.convenio === 'INSS' && (params as any).hasTwoCards) {
                const desconto = (params as any).negativeCardValue || 81.05;
                params.valorParcela = Math.max(0, (params.valorParcela || 0) - desconto);
            }

            // Fallback de Taxa
            if (!params.taxaJurosMensal) {
                const pmt = params.valorParcela || 0;
                const pv = params.saldoDevedor || 0;
                const total = params.prazoTotal || 0;
                const pagas = params.parcelasPagas || 0;
                const n = params.parcelasRestantes || (total > 0 ? total - pagas : 0);
                if (pmt > 0 && pv > 0 && n > 0) {
                    params.taxaJurosMensal = calculateInterestRateAgent(pv, pmt, n);
                }
            }

            const adminDb = getAdminDb();
            if (!adminDb) return "⚠️ Erro de conexão com o banco.";

            const [banksSnap, rulesSnap, settingsSnap] = await Promise.all([
                adminDb.collection('bankRules').get(),
                adminDb.collection('generalRules').get(),
                adminDb.collection('settings').doc('admin').get()
            ]);

            const banks = banksSnap.docs.map(d => ({ id: d.id, ...d.data() }));
            const rules = rulesSnap.docs.map(d => ({ id: d.id, ...d.data() }));
            const settingsData = settingsSnap.exists ? settingsSnap.data() : {};
            const promotoraPriorities = settingsData?.bankPriorities || {};
            const promotoraInstallments = settingsData?.bankInstallments || {};

            const allOffers = calculateOffers(params, banks, rules, promotoraPriorities, promotoraInstallments, userProfileForSimulation);

            const bankGroups = allOffers.reduce((acc, offer) => {
                if (!acc[offer.name]) acc[offer.name] = { bankName: offer.name, offers: [] };
                acc[offer.name].offers.push(offer);
                return acc;
            }, {} as Record<string, { bankName: string, offers: any[] }>);

            const groupedBanks = Object.values(bankGroups).map(group => {
                const sorted = group.offers.sort((a, b) => a.valorTroco - b.valorTroco);
                return { ...group, offers: sorted, topOffer: sorted[0] };
            }).sort((a, b) => {
                const pA = promotoraPriorities[a.topOffer.id.split('-')[0]] ?? a.topOffer.priority ?? 999;
                const pB = promotoraPriorities[b.topOffer.id.split('-')[0]] ?? b.topOffer.priority ?? 999;
                if (pA !== pB) return (pA || 999) - (pB || 999);
                return a.topOffer.valorTroco - b.topOffer.valorTroco;
            });

            const sanitize = (o: any) => o ? { ...o, logo: undefined } : null;
            const topOffer = sanitize(groupedBanks.length > 0 ? groupedBanks[0].topOffer : null);
            const otherBanks = groupedBanks.map(g => g.bankName);
            const sampleOffers = groupedBanks.map(g => sanitize(g.topOffer)).slice(0, 10);

            const simId = crypto.randomUUID();
            try {
                await adminDb.collection('simulations').doc(simId).set({
                    userId: userProfileForSimulation.uid || 'bot',
                    userName: userProfileForSimulation.name || 'WhatsApp',
                    userAvatar: userProfileForSimulation.logoUrl || userProfileForSimulation.avatarUrl || '',
                    convenio: params.convenio,
                    valorParcela: params.valorParcela,
                    saldoDevedor: params.saldoDevedor,
                    selectedOffer: topOffer,
                    topOffer: topOffer?.name || '',
                    createdAt: new Date(),
                    origin: 'whatsapp'
                });
            } catch (e) { console.error("Sim Save Error:", e); }

            const followUp = await ai.models.generateContent({
                model: "gemini-3-flash-preview",
                contents: [
                    ...contents,
                    firstCandidate?.content || { role: "model", parts: [{ functionCall: functionCalls[0] }] },
                    {
                        role: "function",
                        parts: [{
                            functionResponse: {
                                name: "calculate_client_loan_offers",
                                response: {
                                    offersCount: allOffers.length,
                                    banksCount: otherBanks.length,
                                    bestTroco: topOffer,
                                    allBanksWithOffers: otherBanks,
                                    sampleOffers,
                                    otherTablesOfBestBank: groupedBanks.length > 0 ? groupedBanks[0].offers.slice(1, 6).map(sanitize) : []
                                }
                            }
                        }]
                    }
                ],
                config: { systemInstruction }
            });

            // Se o followUp não trouxer texto, geramos um fallback estruturado
            if (!followUp.text) {
                if (topOffer) {
                    return `Encontramos uma oferta ideal para você no *${topOffer.name}*!\n\n📊 *Tabela:* ${topOffer.tabela}\n💰 *Troco Estimado:* R$ ${topOffer.valorTroco.toLocaleString('pt-BR')}\n📄 *Novo Contrato:* R$ ${topOffer.valorContrato.toLocaleString('pt-BR')}\n💲 *Parcela:* R$ ${params.valorParcela}\n⏳ *Prazo:* ${topOffer.prazoRefinPort || 96} meses\n\nOutros Bancos: ${otherBanks.join(', ')}`;
                }
                return "Simulação concluída, mas não encontramos ofertas viáveis para o seu perfil no momento.";
            }

            return followUp.text;
        }

        return firstCandidate?.content?.parts?.find((p: any) => p.text)?.text || (result as any).text || "Como posso ajudar na sua simulação hoje?";

    } catch (error: any) {
        console.error("Critical Agent Error:", error);
        return "Desculpe, tive um problema técnico ao processar sua simulação. Pode tentar novamente em alguns instantes?";
    }
}
